
conky.config = {
    -- window position and size
    alignment = 'top_left',
    gap_x = 10,
    gap_y = 10,
    minimum_height = 434,
    minimum_width = 700,
    maximum_width = 700,
    background = false,
    border_width = 1,
    own_window = true,
    own_window_class = 'conky',
    own_window_type = 'normal',
    -- Colors
    font = 'DepartureMono Nerd Font:size=10',
    font1 = 'DepartureMono Nerd Font:size=10',
    color2 = '#C5C8C6',                        -- accent
    color1 = '#DBBC7F',                        -- accent dimmed
    own_window_transparent = false,            -- transparency
    own_window_argb_visual = false,             -- transparency
    own_window_argb_value = 195,               -- transparency [0 -255]
    own_window_colour = '#1b1f20',             -- bg color [comment to full transparency]
    default_color = 'white',                   -- default colors
    default_outline_color = 'white',           -- default colors
    default_shade_color = 'white',             -- default colors
    double_buffer = true,                      -- removes flickering
    draw_borders = false,                      -- borders (window)
    draw_graph_borders = true,                 -- borders (graphs)
    draw_outline = false,                      -- border (text)
    draw_shades = false,                       -- shades
    extra_newline = false,                     -- extra newline at the end when writing to stdout
    -- other
    update_interval = 1.0,
    cpu_avg_samples = 4,
    net_avg_samples = 4,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = true,
    show_graph_range = false,
    show_graph_scale = false,
    stippled_borders = 0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,
}

conky.text = [[
${image ~/.config/conky/coco.jpg -p 10,15 -s 280x400}
${goto 310}${color1}${font1}${uid_name 1000}@$nodename
${goto 310}${color2}${font1}------------
${goto 310}${color1}${font1}OS: ${color2}$sysname $machine
${goto 310}${color1}Kernel: ${color2}$kernel
${goto 310}${color1}WM: ${color2}${exec pacman -Q | grep 'bspwm'}
${goto 310}${color1}Time: ${color2}${time %H:%M %a %d %b} [Up: $uptime_short]
${goto 310}${color1}Battery: ${color2}${battery_bar 4, 124 BAT0} ${battery_percent BAT0}%
${goto 310}${color1}CPU: ${color2}${cpubar 4, 124} ${cpu}% ${freq_g}GHz
${goto 310}${color1}Processes: ${color2}${processes}, $running_processes running $running_threads threads 
${goto 310}${color1}RAM: ${color2}${membar 4, 124} $memperc% $mem/${memmax}
${goto 310}${color1}Swap: ${color2}${swapbar 4, 124} $swapperc% $swap/${swapmax}
${goto 310}${color1}VRAM: ${color2}${nvidiabar 4, 124 memperc} ${nvidia memperc}% ${nvidia mem}/${nvidia memtotal}MiB
${goto 310}${color1}Disk: ${color2}${fs_bar 4, 124 /} ${fs_used_perc /}% ${fs_used /}/${fs_size /}
${goto 310}${color1}${font1}Network: ${color2}${wireless_link_bar 4,124 wlan0} ${wireless_link_qual_perc wlan0}% ${wireless_bitrate wlan0}
${goto 310}${color1}SSID: ${color2}${wireless_essid wlan0}
${goto 310}${color1}IP: ${color2}${addr wlan0}

]]
