[colors]
background = '#1E2326'
foreground = '#D3C6AA'
selection-background = '#495156'
selection-foreground = '#E69875'
cursor = '#DBBC7F'
black = '#191e2a'
red = '#E67E80'
green = '#A7C080'
yellow = '#DBBC7F'
blue = '#7FBBB3'
magenta = '#D699B6'
cyan = '#83C092'
white = '#c7c7c7'
light_black = '#686868'
light_red = '#493B40'
light_green = '#3C4841'
light_yellow = '#45443C'
light_blue = '#384B55'
light_magenta = '#463F48'
light_cyan = '#4F5B58'
light_white = '#ffffff'
