#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

export SXHKD_SHELL=/usr/bin/bash
export PAGER=moore
export RANGER_LOAD_DEFAULT_RC=false
export _JAVA_AWT_WM_NONREPARENTING=1
export VISUAL=neovide
export EDITOR=neovide

urxvtd -q &

touch /tmp/options.txt

./bspwm_hiddenwinmenu.sh init &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus	 true
bspc config pointer_modifier	 mod4
bspc config pointer_action1	 move
bspc config pointer_action3	 resize_corner

bspc rule -a '*' state=floating
bspc rule -a urxvtc center=true rectangle=1000x800
bspc rule -a Kitty center=true rectangle=1200x1000
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr

xsettingsd &

picom --config ~/picom.conf &

/usr/bin/dunst &

udiskie &
